import { Trial, GeneratedComment } from "../drizzle/schema";

/**
 * Generate Markdown document for a comment
 */
export function generateMarkdownDocument(
  trial: Trial,
  comment: GeneratedComment
): string {
  const content = `# Commentary on: ${trial.title}

**Journal:** ${trial.journal}  
**DOI:** ${trial.doi || "N/A"}  
**Phase:** ${trial.trialPhase}  
**Publication Date:** ${new Date(trial.publicationDate).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}

---

## Trial Overview

**Indication:** ${trial.indication || "Not specified"}  
**Sample Size:** ${trial.sampleSize ? `${trial.sampleSize} participants` : "Not specified"}  
**Randomization:** ${trial.randomization || "Not specified"}  
**Blinding:** ${trial.blinding || "Not specified"}

**Primary Endpoint:** ${trial.primaryEndpoint || "Not specified"}

**Key Results:**  
${trial.keyResults || "Not available"}

---

## Commentary

${comment.editedText || comment.commentText}

---

## Statistical Metrics

${trial.statisticalMetrics ? `\`\`\`json\n${trial.statisticalMetrics}\n\`\`\`` : "Not available"}

---

## Citation

${trial.authors || "Authors not specified"}. ${trial.title}. *${trial.journal}*. ${new Date(trial.publicationDate).getFullYear()}.${trial.doi ? ` doi:${trial.doi}` : ''}

---

*Generated by Clinical Trials Insight Platform*  
*Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}*  
*Word Count: ${comment.wordCount || 'N/A'}*
`;

  return content;
}

/**
 * Generate plain text document for a comment
 */
export function generatePlainTextDocument(
  trial: Trial,
  comment: GeneratedComment
): string {
  const content = `COMMENTARY ON: ${trial.title}

Journal: ${trial.journal}
DOI: ${trial.doi || "N/A"}
Phase: ${trial.trialPhase}
Publication Date: ${new Date(trial.publicationDate).toLocaleDateString('en-US')}

================================================================================

TRIAL OVERVIEW

Indication: ${trial.indication || "Not specified"}
Sample Size: ${trial.sampleSize ? `${trial.sampleSize} participants` : "Not specified"}
Randomization: ${trial.randomization || "Not specified"}
Blinding: ${trial.blinding || "Not specified"}

Primary Endpoint: ${trial.primaryEndpoint || "Not specified"}

Key Results:
${trial.keyResults || "Not available"}

================================================================================

COMMENTARY

${comment.editedText || comment.commentText}

================================================================================

STATISTICAL METRICS

${trial.statisticalMetrics || "Not available"}

================================================================================

CITATION

${trial.authors || "Authors not specified"}. ${trial.title}. ${trial.journal}. ${new Date(trial.publicationDate).getFullYear()}.${trial.doi ? ` doi:${trial.doi}` : ''}

================================================================================

Generated by Clinical Trials Insight Platform
Date: ${new Date().toLocaleDateString('en-US')}
Word Count: ${comment.wordCount || 'N/A'}
`;

  return content;
}

/**
 * Generate HTML document for a comment (for PDF conversion)
 */
export function generateHTMLDocument(
  trial: Trial,
  comment: GeneratedComment
): string {
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Commentary: ${trial.title}</title>
  <style>
    body {
      font-family: 'Times New Roman', Times, serif;
      line-height: 1.6;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px 20px;
      color: #333;
    }
    h1 {
      font-size: 24px;
      margin-bottom: 20px;
      color: #0D47A1;
    }
    h2 {
      font-size: 18px;
      margin-top: 30px;
      margin-bottom: 15px;
      color: #1976D2;
      border-bottom: 2px solid #1976D2;
      padding-bottom: 5px;
    }
    .metadata {
      background-color: #f5f5f5;
      padding: 15px;
      border-left: 4px solid #0D47A1;
      margin-bottom: 30px;
    }
    .metadata p {
      margin: 5px 0;
    }
    .metadata strong {
      color: #0D47A1;
    }
    .commentary {
      text-align: justify;
      margin: 30px 0;
    }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #ddd;
      font-size: 12px;
      color: #666;
      text-align: center;
    }
    pre {
      background-color: #f5f5f5;
      padding: 15px;
      border-radius: 5px;
      overflow-x: auto;
    }
  </style>
</head>
<body>
  <h1>Commentary on: ${trial.title}</h1>
  
  <div class="metadata">
    <p><strong>Journal:</strong> ${trial.journal}</p>
    <p><strong>DOI:</strong> ${trial.doi || "N/A"}</p>
    <p><strong>Phase:</strong> ${trial.trialPhase}</p>
    <p><strong>Publication Date:</strong> ${new Date(trial.publicationDate).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
  </div>

  <h2>Trial Overview</h2>
  <p><strong>Indication:</strong> ${trial.indication || "Not specified"}</p>
  <p><strong>Sample Size:</strong> ${trial.sampleSize ? `${trial.sampleSize} participants` : "Not specified"}</p>
  <p><strong>Randomization:</strong> ${trial.randomization || "Not specified"}</p>
  <p><strong>Blinding:</strong> ${trial.blinding || "Not specified"}</p>
  <p><strong>Primary Endpoint:</strong> ${trial.primaryEndpoint || "Not specified"}</p>
  
  ${trial.keyResults ? `<p><strong>Key Results:</strong><br>${trial.keyResults.replace(/\n/g, '<br>')}</p>` : ''}

  <h2>Commentary</h2>
  <div class="commentary">
    ${(comment.editedText || comment.commentText).replace(/\n\n/g, '</p><p>').replace(/\n/g, '<br>')}
  </div>

  ${trial.statisticalMetrics ? `
  <h2>Statistical Metrics</h2>
  <pre>${trial.statisticalMetrics}</pre>
  ` : ''}

  <h2>Citation</h2>
  <p>
    ${trial.authors || "Authors not specified"}. ${trial.title}. <em>${trial.journal}</em>. ${new Date(trial.publicationDate).getFullYear()}.${trial.doi ? ` doi:${trial.doi}` : ''}
  </p>

  <div class="footer">
    <p>Generated by Clinical Trials Insight Platform</p>
    <p>Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
    <p>Word Count: ${comment.wordCount || 'N/A'}</p>
  </div>
</body>
</html>`;

  return html;
}

/**
 * Get MIME type for document format
 */
export function getMimeType(format: "markdown" | "pdf" | "word"): string {
  const mimeTypes = {
    markdown: "text/markdown",
    pdf: "application/pdf",
    word: "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
  };
  return mimeTypes[format];
}

/**
 * Get file extension for document format
 */
export function getFileExtension(format: "markdown" | "pdf" | "word"): string {
  const extensions = {
    markdown: "md",
    pdf: "pdf",
    word: "docx"
  };
  return extensions[format];
}
